In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the data
df = pd.read_csv('data/DQN_Breakout.csv', index_col=0)

df.head()

,Unnamed: 0,Episode,Epsilon Value,gamma,alpha,epsilon,epsilon_min,epsilon_decay,batch_size,C,Memory Size,Rewards,Wall Time
0,0,0.0,0.997,0.99,0.0001,0.997,0.1,0.003,500.0,500.0,10000.0,1.0,-0.898625
1,1,1.0,0.994,0.99,0.0001,0.994,0.1,0.003,500.0,500.0,10000.0,4.0,-2.252718
2,2,2.0,0.991,0.99,0.0001,0.991,0.1,0.003,500.0,500.0,10000.0,5.0,-483.175582
3,3,3.0,0.988,0.99,0.0001,0.988,0.1,0.003,500.0,500.0,10000.0,2.0,-732.447057
4,4,4.0,0.985,0.99,0.0001,0.985,0.1,0.003,500.0,500.0,10000.0,1.0,-935.153291